apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        
        # --- YOUR STRICT ALLOWLIST ---
        forward github.com 8.8.8.8 1.1.1.1
        forward google.com 8.8.8.8 1.1.1.1
        # Anything not listed here will be instantly rejected
        # Anything not listed here will be instantly rejected
        
        cache 30
        loop
        reload
        loadbalance
    }